const PERMISSION = {
    VIEW_DASHBOARD: "VIEW_DASHBOARD",
    VIEW_INSTITUTION: "VIEW_INSTITUTION",
}

export const DOMAIN = {
    BACK_OFFICE: "BACK_OFFICE",
    INSTITUTION: "INSTITUTION"
}

export const APP_PERMISSIONS = {
    CAN_VIEW_DASHBOARD: [
        PERMISSION.VIEW_DASHBOARD
    ],
    CAN_VIEW_INSTITUTIONS: [
        PERMISSION.VIEW_INSTITUTION
    ],
}