ALTER TABLE departments
  ADD COLUMN IF NOT EXISTS description VARCHAR(255) NOT NULL DEFAULT '';

ALTER TABLE departments
  ADD COLUMN IF NOT EXISTS manager_name VARCHAR(255) NOT NULL DEFAULT '';

ALTER TABLE departments
  ADD COLUMN IF NOT EXISTS no_of_employees INTEGER NOT NULL DEFAULT 0;
